export const categories = [
  'Personal Items',
  'Electronics',
  'Identification',
  'Clothing',
  'Books and Notebooks',
  "Toys and Children's Items",
  'Transportation Items',
  'Travel Items',
  'Sports Equipment',
  'Musical Instruments',
  'Pets',
  'Office Items',
  'Tools',
  'Miscellaneous Items',
]
